jwt:
  secret: ${JWT_SECRET:thisIsASecureSecretValueOf32CharactersOrMore}
server:
  port: 8080
spring:
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: service1
          uri: ${SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/hello
