services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: user
        MONGO_INITDB_ROOT_PASSWORD: pass
